In [5]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/projet_IA_cyber/utils

ModuleNotFoundError: No module named 'google'

# TF-IDF

In [6]:
import importlib
import logging
import pandas as pd
import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)
logging.basicConfig(level=logging.INFO)

# 1. Chargement
print(">>> Chargement des données...")
df = loading.binary_load_data('../data/cyberbullying_tweets.csv', negative_class='not_cyberbullying')

# 2. Features de base
print(">>> Feature Engineering...")
df = feature_engineering.apply_feature_engineering(df, column_name='text')

# 3. TF-IDF
print(">>> Embedding TF-IDF...")
df = embedder.apply_tfidf_embedding(df, 'text', max_features=1000, ngram_range=(1, 2))

# 4. Sauvegarde
output_path = '../data_clean/df_tfidf.csv'
df.to_csv(output_path, index=False)
print(f"Done! Sauvegardé dans {output_path} | Shape: {df.shape}")
print(df.head())

>>> Chargement des données...
>>> Feature Engineering...
>>> Embedding TF-IDF...
Done! Sauvegardé dans ../data_clean/df_tfidf.csv | Shape: (46426, 1008)
                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_tfidf_0  text_tfidf_1  ...  text_tfidf_990  text_tfidf_991  \
0           0.0           0.0  ...             0.0             0.0
1           0.0           0.0  ...             0.0             0.0
2           0.0           0.0  ...             0.0             0.0
3           0.0           0.0  ...             0.0             0.0
4           0.0           0.0  ...             0.0             0.0

   text_tfidf_992  text_tfidf_993  text_tfidf_994  text_tfidf_995  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0
3             0.0             0.0             0.0             0.0
4             0.0             0.0             0.0             0.0

   text_tfidf_996  text_tfidf_997  text_tfidf_998  text_tfidf_999
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0
3             0.0             0.0             0.0             0.0
4             0.0             0.0             0.0             0.0

[5 rows x 1008 columns]

# Bag of Words

In [7]:
import importlib
import logging
import pandas as pd
import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# 1. Chargement
print(">>> Chargement des données...")
df = loading.binary_load_data('../data/cyberbullying_tweets.csv', negative_class='not_cyberbullying')

# 2. Features de base
print(">>> Feature Engineering...")
df = feature_engineering.apply_feature_engineering(df, column_name='text')

# 3. Bag of Words
print(">>> Embedding BoW...")
df = embedder.apply_bow_embedding(df, 'text', max_features=1000, ngram_range=(1, 1))

# 4. Sauvegarde
output_path = '../data_clean/df_bow.csv'
df.to_csv(output_path, index=False)
print(f"Done! Sauvegardé dans {output_path} | Shape: {df.shape}")
print(df.head())

>>> Chargement des données...
>>> Feature Engineering...
>>> Embedding BoW...
Done! Sauvegardé dans ../data_clean/df_bow.csv | Shape: (46426, 1008)
                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bow_0  text_bow_1  ...  text_bow_990  text_bow_991  text_bow_992  \
0           0           0  ...             0             0             0
1           0           0  ...             0             0             0
2           0           0  ...             0             0             0
3           0           0  ...             0             0             0
4           0           0  ...             0             0             0

   text_bow_993  text_bow_994  text_bow_995  text_bow_996  text_bow_997  \
0             0             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   text_bow_998  text_bow_999
0             0             0
1             0             0
2             0             0
3             0             0
4             0             0

[5 rows x 1008 columns]

# Glove

## Train Glove

In [8]:
!pip install mittens
import importlib
import logging

import pandas as pd
import numpy as np

import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger un petit échantillon de données
df = loading.binary_load_data('../data/cyberbullying_tweets.csv',
    negative_class='not_cyberbullying',
    n_samples=10000
    )

df = feature_engineering.apply_feature_engineering(df, column_name='text')

embedder.apply_glove_embedding(df, 'text',
    retrain=True,
    vector_size=100,
    save_path='../data/glove_model.pkl')

Requirement already satisfied: mittens in c:\users\laury\downloads\projet_ia_cyber-20260121t221255z-3-001\projet_ia_cyber\.venv\lib\site-packages (0.2)
Requirement already satisfied: numpy in c:\users\laury\downloads\projet_ia_cyber-20260121t221255z-3-001\projet_ia_cyber\.venv\lib\site-packages (from mittens) (2.4.0)

INFO:embedder:Construction rapide de la matrice de co-occurrence...
INFO:embedder:Vocabulaire : 7533 mots | Matrice : (7533, 7533)
INFO:embedder:Entraînement GloVe (Mittens)...

>>> Entraînement GloVe...

Iteration 100: error 920.7185

>>> Transformation (Parallèle)...

,text,type,text_words,text_chars,text_mentions,text_hashtags,text_urls,text_capitals,text_glove_0,text_glove_1,...,text_glove_90,text_glove_91,text_glove_92,text_glove_93,text_glove_94,text_glove_95,text_glove_96,text_glove_97,text_glove_98,text_glove_99
0,these guys finally exhausted themselves yay qu...,0,9,80,0,0,1,5,0.171261,-0.015099,...,0.152341,0.087619,0.178110,-0.209974,-0.215857,-0.090419,0.118411,-0.117437,0.114178,0.046531
1,news from prayerthatheals org a spiritual defe...,0,11,105,0,1,1,7,0.195851,-0.124340,...,-0.023077,0.101299,-0.111513,-0.007660,-0.246263,-0.168885,0.030969,-0.037756,0.045381,0.027252
2,that moment when your elementary school bullie...,1,15,108,0,0,0,7,-0.136071,0.578414,...,-0.446369,-0.018569,-0.460797,-0.367828,-0.412255,-0.345812,0.206039,0.002639,-0.150604,-0.271277
3,it depends on how you define meaningful if peo...,0,22,121,1,0,0,0,0.176762,-0.147030,...,0.162137,0.204515,-0.156439,-0.204399,0.016159,-0.257679,0.185182,-0.087798,0.172297,0.125850
4,why exactly do u have his slipper o o u bully ...,1,19,113,3,0,0,5,0.485172,-0.376289,...,-0.102483,0.265932,-0.317208,-0.196134,-0.584397,-0.393772,0.321033,-0.420972,0.425953,0.089247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9724,the love you never gave i give to you,0,9,38,0,0,0,2,-0.027639,0.327329,...,-0.106995,0.150918,0.106982,-0.084827,-0.213011,-0.195195,0.130757,-0.171551,-0.160365,-0.185317
9725,i m not sexist but there s something so off pu...,1,17,135,1,1,1,4,0.141319,0.033006,...,0.815055,0.268101,-0.131546,-0.230078,-0.142912,-0.256295,0.327341,-0.178122,0.212675,-0.095170
9726,this reminds me of a school yard bully session...,1,28,145,0,0,0,5,0.367931,-0.096305,...,0.257107,0.127318,-0.120511,-0.086599,-0.187019,-0.175142,0.129310,-0.074982,0.129931,0.308036
9727,i just know if jennie went to my school she wo...,1,13,58,0,0,0,0,0.585479,0.170789,...,0.468465,0.325044,-0.195063,-0.372936,-0.425612,-0.433560,0.389024,-0.479368,0.373829,0.528989
9728,fuck you dumb nigger,1,5,33,1,0,0,3,0.158228,-0.552797,...,-0.633912,0.407152,0.392244,-0.353042,0.308886,-0.344279,0.483510,-0.568520,0.287242,-0.242274

## Use Glove

In [ ]:
import importlib
import logging

import pandas as pd
import numpy as np

import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger un petit échantillon de données
df = loading.binary_load_data('../data/cyberbullying_tweets.csv',
    negative_class='not_cyberbullying',

    )

df = feature_engineering.apply_feature_engineering(df, column_name='text')

df = embedder.apply_glove_embedding(df, 'text',
    method='mean',
    glove_path='../data/glove_model.pkl',
    retrain=False,
    vector_size=100)

print(df.head())


# 4. Sauvegarde
output_path = '../data_clean/df_glove.csv'
df.to_csv(output_path, index=False)
print(f"Done! Sauvegardé dans {output_path} | Shape: {df.shape}")
print(df.head())

>>> Chargement GloVe : ../data/glove_model.pkl...
>>> Transformation (Parallèle)...
                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_glove_0  text_glove_1  ...  text_glove_90  text_glove_91  \
0      0.206895     -0.280024  ...       0.113686       0.132488
1      0.479369      0.749616  ...       0.416514      -0.187889
2      0.042039      0.107879  ...       0.030285       0.013945
3      0.164274     -0.084731  ...       0.071697      -0.017353
4     -0.329512     -0.264358  ...       0.148228      -0.011224

   text_glove_92  text_glove_93  text_glove_94  text_glove_95  text_glove_96  \
0      -0.370417      -0.327338      -0.002261       0.125474      -0.082238
1      -0.598938      -0.955688       0.655495       0.460926      -0.594901
2      -0.111335      -0.208298      -0.142282       0.058012      -0.078507
3      -0.226096       0.130873       0.028071       0.092109      -0.141305
4      -0.165151      -0.122784       0.144377       0.043260      -0.140520

   text_glove_97  text_glove_98  text_glove_99
0       0.076546       0.011300       0.239562
1      -0.836409      -0.559624       0.357593
2      -0.042220      -0.003343      -0.078756
3      -0.116824       0.038850       0.051746
4       0.105650      -0.163599       0.163364

[5 rows x 108 columns]
Done! Sauvegardé dans ../data_clean/df_glove.csv | Shape: (46426, 108)
                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_glove_0  text_glove_1  ...  text_glove_90  text_glove_91  \
0      0.206895     -0.280024  ...       0.113686       0.132488
1      0.479369      0.749616  ...       0.416514      -0.187889
2      0.042039      0.107879  ...       0.030285       0.013945
3      0.164274     -0.084731  ...       0.071697      -0.017353
4     -0.329512     -0.264358  ...       0.148228      -0.011224

   text_glove_92  text_glove_93  text_glove_94  text_glove_95  text_glove_96  \
0      -0.370417      -0.327338      -0.002261       0.125474      -0.082238
1      -0.598938      -0.955688       0.655495       0.460926      -0.594901
2      -0.111335      -0.208298      -0.142282       0.058012      -0.078507
3      -0.226096       0.130873       0.028071       0.092109      -0.141305
4      -0.165151      -0.122784       0.144377       0.043260      -0.140520

   text_glove_97  text_glove_98  text_glove_99
0       0.076546       0.011300       0.239562
1      -0.836409      -0.559624       0.357593
2      -0.042220      -0.003343      -0.078756
3      -0.116824       0.038850       0.051746
4       0.105650      -0.163599       0.163364

[5 rows x 108 columns]

# Bert Embedder

## Train Bert

In [ ]:
import importlib
import logging

import pandas as pd
import numpy as np

import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger un petit échantillon de données
df = loading.binary_load_data('../data/cyberbullying_tweets.csv',
    negative_class='not_cyberbullying',
    n_samples=5000
    )

df = feature_engineering.apply_feature_engineering(df, column_name='text')


# Utilisation de BERT (MiniLM)
df = embedder.apply_bert_embedding(
    df,
    'text',
    model_name='all-MiniLM-L6-v2', # Modèle rapide par défaut
    retrain=True,
    save_path='../data/my_finetuned_bert'
)

print(df.head())

>>> Fine-tuning BERT...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

WARNING:sentence_transformers.losses.DenoisingAutoEncoderLoss:When tie_encoder_decoder=True, the decoder_name_or_path will be invalid.
Some weights of BertLMHeadModel were not initialized from the model checkpoint at sentence-transformers/all-MiniLM-L6-v2 and are newly initialized: ['bert.encoder.layer.0.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.0.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.0.crossattention.output.dense.bias', 'bert.encoder.layer.0.crossattention.output.dense.weight', 'bert.encoder.layer.0.crossattention.self.key.bias', 'bert.encoder.layer.0.crossattention.self.key.weight', 'bert.encoder.layer.0.crossattention.self.query.bias', 'bert.encoder.layer.0.crossattention.self.query.weight', 'bert.encoder.layer.0.crossattention.self.value.bias', 'bert.encoder.layer.0.crossattention.self.value.weight', 'bert.encoder.layer.1.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.1.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.1.crossattention.output.dense.bias', 'bert.encoder.layer.1.crossattention.output.dense.weight', 'bert.encoder.layer.1.crossattention.self.key.bias', 'bert.encoder.layer.1.crossattention.self.key.weight', 'bert.encoder.layer.1.crossattention.self.query.bias', 'bert.encoder.layer.1.crossattention.self.query.weight', 'bert.encoder.layer.1.crossattention.self.value.bias', 'bert.encoder.layer.1.crossattention.self.value.weight', 'bert.encoder.layer.2.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.2.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.2.crossattention.output.dense.bias', 'bert.encoder.layer.2.crossattention.output.dense.weight', 'bert.encoder.layer.2.crossattention.self.key.bias', 'bert.encoder.layer.2.crossattention.self.key.weight', 'bert.encoder.layer.2.crossattention.self.query.bias', 'bert.encoder.layer.2.crossattention.self.query.weight', 'bert.encoder.layer.2.crossattention.self.value.bias', 'bert.encoder.layer.2.crossattention.self.value.weight', 'bert.encoder.layer.3.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.3.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.3.crossattention.output.dense.bias', 'bert.encoder.layer.3.crossattention.output.dense.weight', 'bert.encoder.layer.3.crossattention.self.key.bias', 'bert.encoder.layer.3.crossattention.self.key.weight', 'bert.encoder.layer.3.crossattention.self.query.bias', 'bert.encoder.layer.3.crossattention.self.query.weight', 'bert.encoder.layer.3.crossattention.self.value.bias', 'bert.encoder.layer.3.crossattention.self.value.weight', 'bert.encoder.layer.4.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.4.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.4.crossattention.output.dense.bias', 'bert.encoder.layer.4.crossattention.output.dense.weight', 'bert.encoder.layer.4.crossattention.self.key.bias', 'bert.encoder.layer.4.crossattention.self.key.weight', 'bert.encoder.layer.4.crossattention.self.query.bias', 'bert.encoder.layer.4.crossattention.self.query.weight', 'bert.encoder.layer.4.crossattention.self.value.bias', 'bert.encoder.layer.4.crossattention.self.value.weight', 'bert.encoder.layer.5.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.5.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.5.crossattention.output.dense.bias', 'bert.encoder.layer.5.crossattention.output.dense.weight', 'bert.encoder.layer.5.crossattention.self.key.bias', 'bert.encoder.layer.5.crossattention.self.key.weight', 'bert.encoder.layer.5.crossattention.self.query.bias', 'bert.encoder.layer.5.crossattention.self.query.weight', 'bert.encoder.layer.5.crossattention.self.value.bias', 'bert.encoder.layer.5.crossattention.self.value.weight', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The following encoder weights were not tied to the decoder ['bert/pooler']

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

>>> Encodage BERT (Batch: 64)...

Batches:   0%|          | 0/77 [00:00<?, ?it/s]

                                                text  type  text_words  \
0  sir as you can see how thz idiot spreading hat...     1          51
1      i ll shoot you a dm when i ve got a solid eta     0          12
2  rt we should do a challenge where everyone tur...     1          22
3  rt driverless cars that would be an improvemen...     1          18
4       rt sj neo database queries as social justice     1           9

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0         284              0              0          0              5
1          60              1              0          0              7
2         136              1              0          0              2
3         113              1              1          0              8
4          59              1              0          0              5

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0     0.104912     0.020990  ...       0.096235       0.018072      -0.015316
1     0.088013     0.010359  ...       0.076507      -0.002804      -0.003672
2     0.084638     0.023975  ...       0.096538       0.003993       0.004558
3     0.076763     0.031784  ...       0.093336      -0.008312      -0.000034
4     0.073654     0.025196  ...       0.102396      -0.019116       0.019843

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0      -0.013514       0.096743       0.061197       0.025396      -0.000582
1      -0.012349       0.099438       0.057292       0.025302      -0.018846
2      -0.018403       0.086213       0.060107       0.015545      -0.004028
3      -0.012759       0.094175       0.068499       0.026535       0.012312
4      -0.008122       0.075850       0.041064       0.025237      -0.008022

   text_bert_382  text_bert_383
0       0.019360       0.001189
1       0.033700      -0.011205
2       0.028540       0.000939
3       0.010298       0.001733
4       0.012368       0.002740

[5 rows x 392 columns]

## Use Bert

In [ ]:
import importlib
import logging

import pandas as pd
import numpy as np

import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger un petit échantillon de données
df = loading.binary_load_data('../data/cyberbullying_tweets.csv',
    negative_class='not_cyberbullying',
    )

df = feature_engineering.apply_feature_engineering(df, column_name='text')

df = embedder.apply_bert_embedding(df,
    column_name='text',
    save_path='../data/my_finetuned_bert',
    retrain=False,
    batch_size=64
)

print(df.head())


# 4. Sauvegarde
output_path = '../data_clean/df_bert.csv'
df.to_csv(output_path, index=False)
print(f"Done! Sauvegardé dans {output_path} | Shape: {df.shape}")
print(df.head())

>>> Chargement BERT : ../data/my_finetuned_bert...
>>> Encodage BERT (Batch: 64)...

Batches:   0%|          | 0/726 [00:00<?, ?it/s]

                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0     0.076458     0.010070  ...       0.091763      -0.009679       0.002900
1     0.086058     0.032364  ...       0.077976       0.002378      -0.002804
2     0.071079     0.026555  ...       0.081765      -0.029196       0.010075
3     0.091022     0.029104  ...       0.083717       0.006319       0.009490
4     0.105491     0.015107  ...       0.099014       0.014696       0.002618

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0      -0.009634       0.085054       0.061820       0.022002      -0.014447
1       0.000088       0.071231       0.058411       0.016805      -0.006760
2      -0.015220       0.072448       0.063828       0.022472      -0.013993
3      -0.008404       0.074642       0.058552       0.015657      -0.022701
4      -0.025001       0.108536       0.057059       0.010314       0.018239

   text_bert_382  text_bert_383
0       0.017131      -0.003866
1       0.011546      -0.011316
2       0.004585      -0.020443
3       0.020141       0.005130
4       0.007296      -0.000966

[5 rows x 392 columns]
Done! Sauvegardé dans ../data_clean/df_bert.csv | Shape: (46426, 392)
                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0     0.076458     0.010070  ...       0.091763      -0.009679       0.002900
1     0.086058     0.032364  ...       0.077976       0.002378      -0.002804
2     0.071079     0.026555  ...       0.081765      -0.029196       0.010075
3     0.091022     0.029104  ...       0.083717       0.006319       0.009490
4     0.105491     0.015107  ...       0.099014       0.014696       0.002618

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0      -0.009634       0.085054       0.061820       0.022002      -0.014447
1       0.000088       0.071231       0.058411       0.016805      -0.006760
2      -0.015220       0.072448       0.063828       0.022472      -0.013993
3      -0.008404       0.074642       0.058552       0.015657      -0.022701
4      -0.025001       0.108536       0.057059       0.010314       0.018239

   text_bert_382  text_bert_383
0       0.017131      -0.003866
1       0.011546      -0.011316
2       0.004585      -0.020443
3       0.020141       0.005130
4       0.007296      -0.000966

[5 rows x 392 columns]

# RoBERTa
## Train

In [9]:
import importlib
import logging

import pandas as pd
import numpy as np

import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger un petit échantillon de données
df = loading.binary_load_data('../data/cyberbullying_tweets.csv',
    negative_class='not_cyberbullying',
    n_samples=5000
    )

df = feature_engineering.apply_feature_engineering(df, column_name='text')


# Utilisation de BERT (MiniLM)
df = embedder.apply_bert_embedding(
    df,
    'text',
    model_name='sentence-transformers/paraphrase-distilroberta-base-v1', # Modèle rapide par défaut
    retrain=True,
    save_path='../data/my_finetuned_roberta'
)

print(df.head())

c:\Users\laury\Downloads\projet_IA_cyber-20260121T221255Z-3-001\projet_IA_cyber\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:embedder:Chargement BERT : sentence-transformers/paraphrase-distilroberta-base-v1...
INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cpu
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/paraphrase-distilroberta-base-v1

>>> Fine-tuning BERT...

WARNING:sentence_transformers.losses.DenoisingAutoEncoderLoss:When tie_encoder_decoder=True, the decoder_name_or_path will be invalid.
The following generation flags are not valid and may be ignored: ['output_hidden_states']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Some weights of RobertaForCausalLM were not initialized from the model checkpoint at sentence-transformers/paraphrase-distilroberta-base-v1 and are newly initialized: ['lm_head.bias', 'lm_head.decoder.bias', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'roberta.encoder.layer.0.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.0.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.0.crossattention.output.dense.bias', 'roberta.encoder.layer.0.crossattention.output.dense.weight', 'roberta.encoder.layer.0.crossattention.self.key.bias', 'roberta.encoder.layer.0.crossattention.self.key.weight', 'roberta.encoder.layer.0.crossattention.self.query.bias', 'roberta.encoder.layer.0.crossattention.self.query.weight', 'roberta.encoder.layer.0.crossattention.self.value.bias', 'roberta.encoder.layer.0.crossattention.self.value.weight', 'roberta.encoder.layer.1.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.1.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.1.crossattention.output.dense.bias', 'roberta.encoder.layer.1.crossattention.output.dense.weight', 'roberta.encoder.layer.1.crossattention.self.key.bias', 'roberta.encoder.layer.1.crossattention.self.key.weight', 'roberta.encoder.layer.1.crossattention.self.query.bias', 'roberta.encoder.layer.1.crossattention.self.query.weight', 'roberta.encoder.layer.1.crossattention.self.value.bias', 'roberta.encoder.layer.1.crossattention.self.value.weight', 'roberta.encoder.layer.2.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.2.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.2.crossattention.output.dense.bias', 'roberta.encoder.layer.2.crossattention.output.dense.weight', 'roberta.encoder.layer.2.crossattention.self.key.bias', 'roberta.encoder.layer.2.crossattention.self.key.weight', 'roberta.encoder.layer.2.crossattention.self.query.bias', 'roberta.encoder.layer.2.crossattention.self.query.weight', 'roberta.encoder.layer.2.crossattention.self.value.bias', 'roberta.encoder.layer.2.crossattention.self.value.weight', 'roberta.encoder.layer.3.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.3.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.3.crossattention.output.dense.bias', 'roberta.encoder.layer.3.crossattention.output.dense.weight', 'roberta.encoder.layer.3.crossattention.self.key.bias', 'roberta.encoder.layer.3.crossattention.self.key.weight', 'roberta.encoder.layer.3.crossattention.self.query.bias', 'roberta.encoder.layer.3.crossattention.self.query.weight', 'roberta.encoder.layer.3.crossattention.self.value.bias', 'roberta.encoder.layer.3.crossattention.self.value.weight', 'roberta.encoder.layer.4.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.4.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.4.crossattention.output.dense.bias', 'roberta.encoder.layer.4.crossattention.output.dense.weight', 'roberta.encoder.layer.4.crossattention.self.key.bias', 'roberta.encoder.layer.4.crossattention.self.key.weight', 'roberta.encoder.layer.4.crossattention.self.query.bias', 'roberta.encoder.layer.4.crossattention.self.query.weight', 'roberta.encoder.layer.4.crossattention.self.value.bias', 'roberta.encoder.layer.4.crossattention.self.value.weight', 'roberta.encoder.layer.5.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.5.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.5.crossattention.output.dense.bias', 'roberta.encoder.layer.5.crossattention.output.dense.weight', 'roberta.encoder.layer.5.crossattention.self.key.bias', 'roberta.encoder.layer.5.crossattention.self.key.weight', 'roberta.encoder.layer.5.crossattention.self.query.bias', 'roberta.encoder.layer.5.crossattention.self.query.weight', 'roberta.encoder.layer.5.crossattention.self.value.bias', 'roberta.encoder.layer.5.crossattention.self.value.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The following encoder weights were not tied to the decoder ['roberta/pooler']
INFO:embedder:Fine-tuning BERT (1 epochs)...
c:\Users\laury\Downloads\projet_IA_cyber-20260121T221255Z-3-001\projet_IA_cyber\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

INFO:sentence_transformers.SentenceTransformer:Save model to ../data/my_finetuned_roberta

>>> Encodage BERT (Batch: 64)...

Batches: 100%|██████████| 76/76 [00:52<00:00,  1.46it/s]

                                                text  type  text_words  \
0  i can tell you that i literally study abuse on...     1          26
1  no yoho amp all of us this female included are...     1          42
2                       fuck the pursuer dumb nigger     1           5
3  morgan gave me girl who used to bully you in h...     1          36
4  i bet you dont have a ged or h s d you south n...     1          16

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0         139              1              0          0              0
1         230              1              0          0             14
2          28              0              0          0              1
3         166              0              0          0              1
4          83              1              0          0             52

   text_bert_0  text_bert_1  ...  text_bert_758  text_bert_759  text_bert_760  \
0    -0.036727     0.014316  ...       0.041666      -0.032809      -0.032425
1    -0.037349     0.067301  ...       0.019117      -0.004841       0.008931
2    -0.034827    -0.041382  ...       0.005189      -0.033757       0.020861
3     0.009387     0.051092  ...      -0.023018      -0.008361       0.040910
4    -0.038534     0.023936  ...      -0.006445      -0.010257      -0.030537

   text_bert_761  text_bert_762  text_bert_763  text_bert_764  text_bert_765  \
0       0.038170      -0.029911      -0.048039       0.052660       0.048158
1       0.034525      -0.023279      -0.008974       0.060900       0.042483
2       0.028560       0.039655       0.033173       0.109461      -0.008153
3       0.059906      -0.020119      -0.024960       0.103994       0.042098
4       0.064737      -0.034711       0.006818       0.115587       0.034980

   text_bert_766  text_bert_767
0       0.020930       0.010910
1      -0.006128       0.018458
2      -0.014836      -0.012392
3       0.000855       0.029253
4       0.004951      -0.018467

[5 rows x 776 columns]

### Use

In [ ]:
import importlib
import logging

import pandas as pd
import numpy as np

import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger un petit échantillon de données
df = loading.binary_load_data('../data/cyberbullying_tweets.csv',
    negative_class='not_cyberbullying',
    )

df = feature_engineering.apply_feature_engineering(df, column_name='text')

df = embedder.apply_bert_embedding(df,
    column_name='text',
    save_path='../data/my_finetuned_roberta',
    retrain=False,
    batch_size=64
)

print(df.head())


# 4. Sauvegarde
output_path = '../data_clean/df_roberta.csv'
df.to_csv(output_path, index=False)
print(f"Done! Sauvegardé dans {output_path} | Shape: {df.shape}")
print(df.head())

>>> Chargement BERT : ../data/my_finetuned_roberta...
>>> Encodage BERT (Batch: 64)...

Batches:   0%|          | 0/726 [00:00<?, ?it/s]

                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bert_0  text_bert_1  ...  text_bert_758  text_bert_759  text_bert_760  \
0    -0.020453     0.008961  ...       0.077092      -0.024040       0.009736
1     0.040393     0.015228  ...      -0.026649       0.008764       0.062753
2    -0.024211    -0.009474  ...      -0.016448      -0.008566       0.082585
3    -0.024701    -0.009641  ...       0.029620       0.014738       0.070385
4    -0.053916    -0.003610  ...      -0.034840       0.062457       0.091881

   text_bert_761  text_bert_762  text_bert_763  text_bert_764  text_bert_765  \
0       0.015663       0.012863       0.024636       0.056046       0.106213
1      -0.000561       0.008664       0.049502      -0.060676      -0.001881
2       0.018067      -0.014453      -0.002832      -0.006635       0.052573
3       0.000893      -0.049352       0.009820       0.055252       0.010683
4      -0.014766      -0.078777       0.004630       0.102455       0.019455

   text_bert_766  text_bert_767
0      -0.011934       0.013430
1      -0.004603      -0.007037
2      -0.075032       0.038453
3      -0.002976       0.040884
4      -0.030474       0.062332

[5 rows x 776 columns]
Done! Sauvegardé dans ../data_clean/df_roberta.csv | Shape: (46426, 776)
                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bert_0  text_bert_1  ...  text_bert_758  text_bert_759  text_bert_760  \
0    -0.020453     0.008961  ...       0.077092      -0.024040       0.009736
1     0.040393     0.015228  ...      -0.026649       0.008764       0.062753
2    -0.024211    -0.009474  ...      -0.016448      -0.008566       0.082585
3    -0.024701    -0.009641  ...       0.029620       0.014738       0.070385
4    -0.053916    -0.003610  ...      -0.034840       0.062457       0.091881

   text_bert_761  text_bert_762  text_bert_763  text_bert_764  text_bert_765  \
0       0.015663       0.012863       0.024636       0.056046       0.106213
1      -0.000561       0.008664       0.049502      -0.060676      -0.001881
2       0.018067      -0.014453      -0.002832      -0.006635       0.052573
3       0.000893      -0.049352       0.009820       0.055252       0.010683
4      -0.014766      -0.078777       0.004630       0.102455       0.019455

   text_bert_766  text_bert_767
0      -0.011934       0.013430
1      -0.004603      -0.007037
2      -0.075032       0.038453
3      -0.002976       0.040884
4      -0.030474       0.062332

[5 rows x 776 columns]


## Split data

## BERT

In [ ]:
import importlib
import logging
import pandas as pd
import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)


from sklearn.model_selection import train_test_split

df_bert = pd.read_csv('../data_clean/df_bert.csv')
print(df_bert.head())

X = df_bert[[col for col in df_bert.columns if col.startswith('text_bert')]]  # embeddings
y = df_bert['type']  # target column

                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0    -0.026573     0.082255  ...       0.050917      -0.006585       0.017918
1    -0.025611     0.101780  ...       0.064098      -0.008278       0.011611
2    -0.027470     0.081924  ...       0.035447      -0.011867       0.022204
3    -0.016794     0.109635  ...       0.048091       0.003349       0.025052
4    -0.011197     0.097554  ...       0.046453      -0.001273       0.010876

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0       0.036163       0.048842       0.056797       0.006109       0.003186
1       0.030865       0.038570       0.054028       0.031159       0.021233
2       0.026958       0.030236       0.044706       0.006497       0.015011
3       0.043965       0.067474       0.060560      -0.011037       0.014030
4       0.041317       0.071039       0.070443       0.002954       0.010597

   text_bert_382  text_bert_383
0       0.062542      -0.068393
1       0.073152      -0.069444
2       0.059685      -0.081055
3       0.076370      -0.057879
4       0.055558      -0.054682

[5 rows x 392 columns]

In [ ]:
import importlib
import logging
import pandas as pd
import embedder
import feature_engineering
import loading

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)


from sklearn.model_selection import train_test_split

df_bow = pd.read_csv('../data_clean/df_bow.csv')
print(df_bow.head())

X = df_bow[[col for col in df_bow.columns if col.startswith('text_bert')]]  # embeddings
y = df_bow['type']  # target column

                                                text  type  text_words  \
0          in other words your food was crapilicious     0           9
1                                    why is so white     0          14
2         a classy whore or more red velvet cupcakes     0           9
3  meh p thanks for the heads up but not too conc...     0          18
4  this is an isis account pretending to be a kur...     0          18

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          61              0              2          0              1
1         115              0             10          0             12
2          60              1              0          0              3
3         103              1              0          0              3
4         103              1              0          0             10

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0    -0.026573     0.082255  ...       0.050917      -0.006585       0.017918
1    -0.025611     0.101780  ...       0.064098      -0.008278       0.011611
2    -0.027470     0.081924  ...       0.035447      -0.011867       0.022204
3    -0.016794     0.109635  ...       0.048091       0.003349       0.025052
4    -0.011197     0.097554  ...       0.046453      -0.001273       0.010876

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0       0.036163       0.048842       0.056797       0.006109       0.003186
1       0.030865       0.038570       0.054028       0.031159       0.021233
2       0.026958       0.030236       0.044706       0.006497       0.015011
3       0.043965       0.067474       0.060560      -0.011037       0.014030
4       0.041317       0.071039       0.070443       0.002954       0.010597

   text_bert_382  text_bert_383
0       0.062542      -0.068393
1       0.073152      -0.069444
2       0.059685      -0.081055
3       0.076370      -0.057879
4       0.055558      -0.054682

[5 rows x 392 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train downstream models

We are going to test different embedding - model combinations.

First, let us compare how the different embeddings do with a linear regression

In [ ]:
import importlib
import logging
import pandas as pd
import numpy as np

import train
import evaluate

importlib.reload(train)
importlib.reload(evaluate)

logging.basicConfig(level=logging.INFO)
embedders = ['bert', 'roberta']
models = ['logistic_regression', 'random_forest', 'svm', 'gbm', 'neural_network']
for embedder in embedders :
  print(f"Embedding : {embedder}")
  X_train, X_test, y_train, y_test = train.get_df_split(embedder)
  for model in models :
    print(f"Model : {model}")
    trained_model = train.train_model(model, X_train, y_train)
    y_pred = evaluate.test_model(trained_model, X_test, y_test, "")
    evaluate.balance_accuracy(y_test, y_pred)
    evaluate.mcc(y_test, y_pred)

Embedding : bert
Model : logistic_regression
              precision    recall  f1-score   support

           0       0.66      0.26      0.37      1532
           1       0.87      0.97      0.92      7754

    accuracy                           0.86      9286
   macro avg       0.76      0.62      0.64      9286
weighted avg       0.83      0.86      0.83      9286

Balanced Accuracy: 0.6158948703978945
MCC: 0.3491346351697196
Model : random_forest
              precision    recall  f1-score   support

           0       0.54      0.25      0.34      1532
           1       0.87      0.96      0.91      7754

    accuracy                           0.84      9286
   macro avg       0.70      0.60      0.62      9286
weighted avg       0.81      0.84      0.82      9286

Balanced Accuracy: 0.6027375915134512
MCC: 0.2881184516974644
Model : svm
              precision    recall  f1-score   support

           0       0.94      0.10      0.18      1532
           1       0.85      1.00      0.92      7754

    accuracy                           0.85      9286
   macro avg       0.90      0.55      0.55      9286
weighted avg       0.86      0.85      0.80      9286

Balanced Accuracy: 0.5483752679489606
MCC: 0.27681082697933956
Model : gbm
[LightGBM] [Info] Number of positive: 31193, number of negative: 5947
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.299124 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 97920
[LightGBM] [Info] Number of data points in the train set: 37140, number of used features: 384
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.839876 -> initscore=1.657307
[LightGBM] [Info] Start training from score 1.657307
              precision    recall  f1-score   support

           0       0.62      0.36      0.46      1532
           1       0.88      0.96      0.92      7754

    accuracy                           0.86      9286
   macro avg       0.75      0.66      0.69      9286
weighted avg       0.84      0.86      0.84      9286

Balanced Accuracy: 0.6590181535210329
MCC: 0.3993940619539256
Model : neural_network

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

              precision    recall  f1-score   support

           0       0.57      0.50      0.53      1532
           1       0.90      0.92      0.91      7754

    accuracy                           0.85      9286
   macro avg       0.73      0.71      0.72      9286
weighted avg       0.85      0.85      0.85      9286

Balanced Accuracy: 0.7101863874183358
MCC: 0.4438799441917429
Embedding : roberta
Model : logistic_regression
              precision    recall  f1-score   support

           0       0.63      0.36      0.46      1532
           1       0.88      0.96      0.92      7754

    accuracy                           0.86      9286
   macro avg       0.76      0.66      0.69      9286
weighted avg       0.84      0.86      0.84      9286

Balanced Accuracy: 0.6608315862915191
MCC: 0.40720800571998766
Model : random_forest
              precision    recall  f1-score   support

           0       0.52      0.20      0.29      1532
           1       0.86      0.96      0.91      7754

    accuracy                           0.84      9286
   macro avg       0.69      0.58      0.60      9286
weighted avg       0.80      0.84      0.81      9286

Balanced Accuracy: 0.5805127278702612
MCC: 0.24540785148675448
Model : svm
              precision    recall  f1-score   support

           0       0.72      0.35      0.47      1532
           1       0.88      0.97      0.93      7754

    accuracy                           0.87      9286
   macro avg       0.80      0.66      0.70      9286
weighted avg       0.86      0.87      0.85      9286

Balanced Accuracy: 0.6607405863460685
MCC: 0.43952296673979346
Model : gbm
[LightGBM] [Info] Number of positive: 31193, number of negative: 5947
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.337467 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 37140, number of used features: 768
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.839876 -> initscore=1.657307
[LightGBM] [Info] Start training from score 1.657307
              precision    recall  f1-score   support

           0       0.58      0.35      0.44      1532
           1       0.88      0.95      0.91      7754

    accuracy                           0.85      9286
   macro avg       0.73      0.65      0.68      9286
weighted avg       0.83      0.85      0.84      9286

Balanced Accuracy: 0.6499114244749278
MCC: 0.3728420019138337
Model : neural_network
              precision    recall  f1-score   support

           0       0.51      0.46      0.48      1532
           1       0.90      0.91      0.90      7754

    accuracy                           0.84      9286
   macro avg       0.70      0.69      0.69      9286
weighted avg       0.83      0.84      0.83      9286

Balanced Accuracy: 0.6863759696839701
MCC: 0.38790912940769584

## Analysis
It seems that the model with the best result is thé finetuned BERT with LightGBM

We will test it furthermore by testing it on newfound data

We used another dataset.

## Load new data and embbed using fine-tuned BERT

In [ ]:
import logging

import pandas as pd
import numpy as np
import importlib
import embedder
import feature_engineering
import loading
import train

importlib.reload(train)
logging.basicConfig(level=logging.INFO)

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger nouvelles données
df = pd.read_csv('../data/cyberbullying_new.csv')

df = feature_engineering.apply_feature_engineering(df, column_name='text')

df = embedder.apply_bert_embedding(df,
    column_name='text',
    save_path='../data/my_finetuned_bert',
    retrain=False,
    batch_size=64
)

print(df.head())


# Sauvergarder
output_path = '../data_clean/df_bert_new.csv'
df.to_csv(output_path, index=False)
print(f"Done! Sauvegardé dans {output_path} | Shape: {df.shape}")
print(df.head())

>>> Chargement BERT : ../data/my_finetuned_bert...
>>> Encodage BERT (Batch: 64)...

Batches:   0%|          | 0/237 [00:00<?, ?it/s]

                                                text  type  text_words  \
0        cock suck before you piss around on my work     1           9
1  you are gay or antisemmitian archangel white t...     1         121
2             fuck your filthy mother in the ass dry     1           8
3  get fuck ed up get fuck ed up got a drink that...     1          30
4  stupid peace of shit stop deleting my stuff as...     1          20

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          44              0              0          0              0
1         624              0              0          0              0
2          39              0              0          0              0
3         121              0              0          0              0
4          93              0              0          0              0

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0     0.085606     0.016922  ...       0.077631      -0.020795       0.015627
1     0.089542     0.022056  ...       0.110297      -0.003334       0.006090
2     0.074376     0.018356  ...       0.070980      -0.020201       0.016323
3     0.088812     0.023438  ...       0.063230       0.014148       0.015597
4     0.086589     0.014957  ...       0.085378       0.003563       0.013178

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0      -0.025084       0.065233       0.069033       0.016441      -0.024389
1      -0.031836       0.097964       0.067620       0.031471       0.007517
2      -0.027250       0.063600       0.062426       0.019964       0.004071
3      -0.043354       0.073800       0.061653       0.024019      -0.019149
4      -0.017720       0.083045       0.050983       0.019558      -0.011692

   text_bert_382  text_bert_383
0       0.010695      -0.000872
1       0.013214       0.000122
2       0.009696      -0.019021
3       0.038014      -0.024509
4       0.031661       0.002204

[5 rows x 392 columns]
Done! Sauvegardé dans ../data_clean/df_bert_new.csv | Shape: (15143, 392)
                                                text  type  text_words  \
0        cock suck before you piss around on my work     1           9
1  you are gay or antisemmitian archangel white t...     1         121
2             fuck your filthy mother in the ass dry     1           8
3  get fuck ed up get fuck ed up got a drink that...     1          30
4  stupid peace of shit stop deleting my stuff as...     1          20

   text_chars  text_mentions  text_hashtags  text_urls  text_capitals  \
0          44              0              0          0              0
1         624              0              0          0              0
2          39              0              0          0              0
3         121              0              0          0              0
4          93              0              0          0              0

   text_bert_0  text_bert_1  ...  text_bert_374  text_bert_375  text_bert_376  \
0     0.085606     0.016922  ...       0.077631      -0.020795       0.015627
1     0.089542     0.022056  ...       0.110297      -0.003334       0.006090
2     0.074376     0.018356  ...       0.070980      -0.020201       0.016323
3     0.088812     0.023438  ...       0.063230       0.014148       0.015597
4     0.086589     0.014957  ...       0.085378       0.003563       0.013178

   text_bert_377  text_bert_378  text_bert_379  text_bert_380  text_bert_381  \
0      -0.025084       0.065233       0.069033       0.016441      -0.024389
1      -0.031836       0.097964       0.067620       0.031471       0.007517
2      -0.027250       0.063600       0.062426       0.019964       0.004071
3      -0.043354       0.073800       0.061653       0.024019      -0.019149
4      -0.017720       0.083045       0.050983       0.019558      -0.011692

   text_bert_382  text_bert_383
0       0.010695      -0.000872
1       0.013214       0.000122
2       0.009696      -0.019021
3       0.038014      -0.024509
4       0.031661       0.002204

[5 rows x 392 columns]
11284    1
44732    1
38158    1
860      0
15795    1
Name: type, dtype: int64
19927    1
564      0
3243     0
6887     0
25542    1
Name: type, dtype: int64
[LightGBM] [Info] Number of positive: 31193, number of negative: 5947
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.326677 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 97920
[LightGBM] [Info] Number of data points in the train set: 37140, number of used features: 384
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.839876 -> initscore=1.657307
[LightGBM] [Info] Start training from score 1.657307
Classification report for test set:
{'0': {'precision': 0.5515729757607014, 'recall': 0.6751893939393939, 'f1-score': 0.6071529946068691, 'support': 6336.0}, '1': {'precision': 0.7214024637877352, 'recall': 0.6050868627228341, 'f1-score': 0.6581449919723354, 'support': 8807.0}, 'accuracy': 0.6344185432212903, 'macro avg': {'precision': 0.6364877197742183, 'recall': 0.640138128331114, 'f1-score': 0.6326489932896022, 'support': 15143.0}, 'weighted avg': {'precision': 0.6503439128969417, 'recall': 0.6344185432212903, 'f1-score': 0.636809371863533, 'support': 15143.0}}

## Train chosen model

## Tune hyperparameters

In [ ]:
import logging

import pandas as pd
import numpy as np
import importlib
import embedder
import feature_engineering
import loading
import train
import pickle
importlib.reload(train)
logging.basicConfig(level=logging.INFO)

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Séparer
X_train, X_test, y_train, y_test = train.get_df_split('bert')
train.hyperparam_search(X_train, y_train)

In [ ]:
import logging

import pandas as pd
import numpy as np
import importlib
import embedder
import feature_engineering
import loading
import train
import pickle
importlib.reload(train)
logging.basicConfig(level=logging.INFO)

importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Séparer
X_train, X_test, y_train, y_test = train.get_df_split('bert')

print(y_train.tail())
print(y_test.head())

# Entrainer light GBM
trained_model = train.train_model('gbm', X_train, y_train)

11284    1
44732    1
38158    1
860      0
15795    1
Name: type, dtype: int64
19927    1
564      0
3243     0
6887     0
25542    1
Name: type, dtype: int64
[LightGBM] [Info] Number of positive: 31193, number of negative: 5947
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.205417 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 97920
[LightGBM] [Info] Number of data points in the train set: 37140, number of used features: 384
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.839876 -> initscore=1.657307
[LightGBM] [Info] Start training from score 1.657307

### Choose model

In [ ]:
model_name = 'gbm'

In [ ]:
import logging

import pandas as pd
import numpy as np
import importlib
import embedder
import feature_engineering
import loading
import train
import evaluate
logging.basicConfig(level=logging.INFO)

importlib.reload(train)
importlib.reload(evaluate)
importlib.reload(embedder)
importlib.reload(feature_engineering)
importlib.reload(loading)

# Charger le model entrainé
with open(f'../models/{model_name}.pkl', 'rb') as file:
    trained_model = pickle.load(file)

# Charger nouvelles données
df = pd.read_csv('../data_clean/df_bert_new.csv')

X_test_new = df[[col for col in df.columns if col.startswith(f'text_bert')]]
y_test_new = df['type']
y_pred_new = evaluate.test_model(trained_model, X_test_new, y_test_new, "bert_gbm_unseen_data", write=True)

Classification report for test set:
{'0': {'precision': 0.5515729757607014, 'recall': 0.6751893939393939, 'f1-score': 0.6071529946068691, 'support': 6336.0}, '1': {'precision': 0.7214024637877352, 'recall': 0.6050868627228341, 'f1-score': 0.6581449919723354, 'support': 8807.0}, 'accuracy': 0.6344185432212903, 'macro avg': {'precision': 0.6364877197742183, 'recall': 0.640138128331114, 'f1-score': 0.6326489932896022, 'support': 15143.0}, 'weighted avg': {'precision': 0.6503439128969417, 'recall': 0.6344185432212903, 'f1-score': 0.636809371863533, 'support': 15143.0}}

# Performance analysis on unseen data

In [ ]:
y_prob_new = trained_model.predict_proba(X_test_new)[:, 1]

evaluate.roc_curve(y_test_new, y_prob_new)
evaluate.pr_curve(y_test_new, y_prob_new)
evaluate.balance_accuracy(y_test_new, y_pred_new)
evaluate.mcc(y_test_new, y_pred_new)
evaluate.display_confusion_matrix(y_test_new, y_pred_new)
evaluate.find_threshold(y_test_new, y_prob_new)